# Generated by Django 4.0.4 on 2022-05-26 17:02

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=64)),
                ('image_file', models.ImageField(upload_to=pathlib.PurePosixPath('uploads'))),
            ],
        ),
    ]
